#!/bin/sh

die() {
    exit 1
}

# TODO: download gnulib if we don't have it.

# NOTE: This includes way more than is probably necessary just to build
# rm; much of it is included through system.h.  As I'd prefer for this not
# to be a permanent fork, I'd rather have a slightly bloated build than to
# go editing files I don't need to.  I don't think this will make rm any
# bigger.
GNULIB_MODULES='
argmatch
closein
closeout
dev-ino
dirname
error
file-type
fts
group-member
inttostr
openat
pathmax
priv-set
progname
propername
quotearg
quote
same-inode
stat-macros
timespec
unlocked-io
vc-list-files
version-etc-fsf
write-any-file
yesno
'

./gnulib/gnulib-tool \
    --import \
    --aux-dir=build-aux \
    --lib=librmfd \
    $GNULIB_MODULES || die

{
    mv lib/Makefile.am lib/gnulib.mk &&
    cp lib/real_Makefile.am lib/Makefile.am
} || die

{
    aclocal --force -I m4 &&
    autoconf --force &&
    autoheader --force &&
    automake --add-missing --copy --force-missing
} || die
