#!/bin/sh

# TODO: download gnulib if we don't have it.

./gnulib/gnulib-tool --import argmatch error priv-set quotearg quote yesno &&
aclocal --force -I m4 &&
autoconf --force &&
autoheader --force &&
automake --add-missing --copy --force-missing
